# -*- coding: utf-8 -*-
"""Practical_5_MLT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOqaSAac02zrwe8HQcd32sSZLREnn5Sw
"""

# https://www.kaggle.com/datasets/yasserh/housing-prices-dataset

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df=pd.read_csv('Housing.csv')

df.head(10)

df['mainroad']=df['mainroad'].apply(lambda x:1 if x=='yes' else 0)
df['guestroom']=df['guestroom'].apply(lambda x:1 if x=='yes' else 0)
df['basement']=df['basement'].apply(lambda x:1 if x=='yes' else 0)
df['hotwaterheating']=df['hotwaterheating'].apply(lambda x:1 if x=='yes' else 0)
df['airconditioning']=df['airconditioning'].apply(lambda x:1 if x=='yes' else 0)
df['prefarea']=df['prefarea'].apply(lambda x:1 if x=='yes' else 0)

mapping = {'unfurnished': 0, 'semifurnished': 1, 'furnished': 2}
df['furnishing_status_encoded'] = df['furnishingstatus'].map(mapping)

df.drop('furnishingstatus',axis=1,inplace=True)

df.isna().sum()

df=df.fillna(df['furnishing_status_encoded'].mode()[0])

df.describe()

from sklearn.model_selection import train_test_split
X=df.drop('furnishing_status_encoded',axis=1)
y=df['furnishing_status_encoded']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor()
knn.fit(X_train,y_train)

from sklearn.metrics import mean_squared_error,r2_score
y_pred=knn.predict(X_test)
mse=mean_squared_error(y_test,y_pred)
print(mse)
r2=r2_score(y_test,y_pred)
print(r2)

