# -*- coding: utf-8 -*-
"""Practical_6_MLT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d9_BSk8kfcKfeCnVaANszyCB55SD6maX
"""

import pandas as pd
from sklearn.datasets import load_iris

iris=load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()

df['target'] = iris.target

df.head()

from sklearn.model_selection import train_test_split
X = df.drop('target', axis=1)
y = df['target']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.naive_bayes import GaussianNB
gb=GaussianNB()
gb.fit(X_train,y_train)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
y_pred=gb.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

